### ISSUE TITLE
Doesn't Work

### ISSUE THREAD

**Issue by pepeonzima1337** [bytecode77/pe-union#7] opened 2021-04-06 19:13 UTC
When binding multiple files for example 
if I bind my exe with a portable software which depends on its files in that folder.
It doesn't get executed or end up broken I tried the portable.exe execution directory option still nothing and the other file gets executed with a huge delay like 1 minute later.

**Comment by bytecode77** [comment] 2021-04-07 07:59
PEunion isn't really optimized to extract entire folder structures onto the disk. Maybe it could be helpful to create a single executable from your portable app, for example by using a self extracting archive. That way, you would have two files.

It should take less than one minute to execute, thogugh. Is the application really large, like > 100MB? Are you dropping hundreds of files? If the latter is the case, maybe creating a single file for the application in the first step and then binding it could work better.

Let me know if you could solve your problem!

**Comment by pepeonzima1337** [comment] 2021-04-07 08:55
Let me explain it you clearly.
We have two main files which we want to bind.
- Portable.exe
Portable l.exe depends on different files it can't run without them. and those files are in the same folder.
- Example.exe 
Example.exe is an independent executeable it doesn't require other files to run.
So the problem I'm facing is when I bind them both Things doesn't work like that 
At first I thought it could be because the 
portable.exe runs in temp folder.
so I tried it with execution directory and still nothing
I tried it with Downloader.
still nothing.
and about the size of the files 
Portable.exe is like only 5mb in size
and the example.exe is like 40kb or something.

**Comment by pepeonzima1337** [comment] 2021-04-07 09:06
I also tried it without encryption

**Comment by bytecode77** [comment] 2021-04-23 15:49
Sorry for the (very) late reply. I was a little busy recently, normally I respond quicker...

Regarding your issue: Can you provide any samples? You can, of course, exclude any confidential files and send me a dummy executable instead. It would be really helpful to have the files and the `.peu` file to analyze the problem. PEunion was never designed to exctract a lot of files and I would need to take a look at that.

-- furthermore --

PEunion's main problems in the current version are:

- It is a binder, however the crypting feature is badly designed, since it does not support in-memory execution. See Issue #8 
- It doesn't handle large files properly (> 100MB), which is a common case, when deploying e.g., a setup.
- Compilation issues that some users have and that are for some reason not reproducible
- A .NET stub is not particularly bad, but it should be a native executable.

That's why I'm already planning a new major release with:

- A native stub that is compiled from an `.asm` file using the FASM compiler, rather than CodeDom
- A **lot** more focus on AV evasion is necessary to make it truly FUD. There are plenty of techniques to consider.
- Full in-memory decryption and execution using process hollowing (RunPE) will be a major focus.
- Of course, dropping files will be a feature, whenever needed.
- Additional features, such as packing executables in `.docx` and similar files.

I will do my best to help you with the current version, while working on the next major release for this year. It will be a much better binder & crypter and the goal is to make it the best available.

**Comment by pepeonzima1337** [comment] 2021-04-23 18:30
Well I guess I have to wait for the newer version you are working on and there is no point to work on this version.
I would prefer you keep working on the newer version and appreciate the reply from the heart bro!
Keep up the good work

**Comment by bytecode77** [comment] 2021-09-09 13:46
# PEunion 4.0.0

The new version of PEunion has been released. All currently open GitHub issues were addressed in the release. Additionally, the new version is a complete rewrite and addresses known issues by fundamental architectural changes.

For more info, please read the main page of PEunion to get an overview over features & functionality.

*This message was posted in all currently open GitHub issues.*

It there are any issues in the new version, I would like to ask everybody to create a new GitHub issue instead of posting here. This way, I will have a better overview over issues in PEunion 3.x vs 4.0

**Closed by bytecode77** 2021-09-09 13:46 UTC
