### ISSUE TITLE
Problem with the download file from url option

### ISSUE THREAD

**Issue by mantoayo** [bytecode77/pe-union#18] opened 2021-11-05 18:27 UTC
I have a problem with the download file from url option. the file is downloaded, but it is not saved in its original form, it has much less kilobytes and therefore does not run. Tested on various upload sites.

**Comment by bytecode77** [comment] 2021-11-05 21:21
Am I guessing correctly that you are using the native stub, not the .NET stub?

What's the exact size in bytes of your file? I'll test it to see where the issue is.

**Comment by mantoayo** [comment] 2021-11-08 14:34
I was try all options, native stub, net32 and net64, each result the same, downloaded file was 9.77 kb everytime but original file  more than 2.1mb, second binded file executed correctly but is not downloaded.

**Comment by bytecode77** [comment] 2021-11-09 08:55
Even with the .NET stub you get the same corrupted file? That's strange.... The native stub has a [custom download implementation](https://github.com/bytecode77/pe-union/blob/master/SlnBin/Stub/pe32/Download.asm) written in asm, but the .NET stub has just [this](https://github.com/bytecode77/pe-union/blob/master/SlnBin/Stub/dotnet/Download.cs):

	using (WebClient webClient = new WebClient())
	{
		return webClient.DownloadData(__url);
	}

I'm just wondering how this could fail... Do you have a link to a file that I can use for testing? So far, I could not reproduce this in any of my testing. If not, I can understand that you don't want to share the URL...

One more thought: Does your file contain parts of the expected file, or does it maybe just contain HTML with an error page returned from the server?

**Comment by Pernat1y** [comment] 2021-11-25 12:52
Just a guess. Do your hosting provides direct URL to binary?

**Comment by bytecode77** [comment] 2021-11-25 15:09
I will close the issue, since OP didn't respond for over two weeks. Also, the very same corrupted file of 9.77 KB got downloaded by both stubs. One of which is written in C# and the other in FASM. It's pretty unlikely that the exact same bug happens with both stubs.

My bet is that something's off with the server where the file is downloaded.

@mantoayo You have to do some analysis, too. I can't see what the content of that 9.77 KB file is. That's why I asked whether it contains HTML output of the server instead of the file itself.

Anyway, I suppose OP has figured out what the problem is. Please feel free to re-open and include more detail, if it still persists.

**Closed by bytecode77** 2021-11-25 15:09 UTC
